In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# load dataset
data = pd.read_csv('/content/drive/MyDrive/Crop Yield/yield_df.csv')
data.head()

Unnamed: 0     Area         Item  Year  hg/ha_yield  \
0           0  Albania        Maize  1990        36613   
1           1  Albania     Potatoes  1990        66667   
2           2  Albania  Rice, paddy  1990        23333   
3           3  Albania      Sorghum  1990        12500   
4           4  Albania     Soybeans  1990         7000   

   average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  
0                         1485.0              121.0     16.37  
1                         1485.0              121.0     16.37  
2                         1485.0              121.0     16.37  
3                         1485.0              121.0     16.37  
4                         1485.0              121.0     16.37

In [ ]:
# remove the unnamed column
data.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
data.head()

Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0  Albania        Maize  1990        36613                         1485.0   
1  Albania     Potatoes  1990        66667                         1485.0   
2  Albania  Rice, paddy  1990        23333                         1485.0   
3  Albania      Sorghum  1990        12500                         1485.0   
4  Albania     Soybeans  1990         7000                         1485.0   

   pesticides_tonnes  avg_temp  
0              121.0     16.37  
1              121.0     16.37  
2              121.0     16.37  
3              121.0     16.37  
4              121.0     16.37

In [ ]:
data['Area'].unique()

array(['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Belarus', 'Belgium', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada',
       'Central African Republic', 'Chile', 'Colombia', 'Croatia',
       'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Eritrea', 'Estonia', 'Finland', 'France', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'India', 'Indonesia', 'Iraq', 'Ireland', 'Italy',
       'Jamaica', 'Japan', 'Kazakhstan', 'Kenya', 'Latvia', 'Lebanon',
       'Lesotho', 'Libya', 'Lithuania', 'Madagascar', 'Malawi',
       'Malaysia', 'Mali', 'Mauritania', 'Mauritius', 'Mexico',
       'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Norway',
       'Pakistan', 'Papua New Guinea', 'Peru', 'Pola

In [ ]:
data['Area'].nunique()

101

In [ ]:
data['Item'].unique()

array(['Maize', 'Potatoes', 'Rice, paddy', 'Sorghum', 'Soybeans', 'Wheat',
       'Cassava', 'Sweet potatoes', 'Plantains and others', 'Yams'],
      dtype=object)

In [ ]:
# shape
data.shape

(28242, 7)

In [ ]:
# checking for null values
data.isna().sum()

Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64

In [ ]:
# get information about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Area                           28242 non-null  object 
 1   Item                           28242 non-null  object 
 2   Year                           28242 non-null  int64  
 3   hg/ha_yield                    28242 non-null  int64  
 4   average_rain_fall_mm_per_year  28242 non-null  float64
 5   pesticides_tonnes              28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.5+ MB


In [ ]:
data.describe()

Year    hg/ha_yield  average_rain_fall_mm_per_year  \
count  28242.000000   28242.000000                    28242.00000   
mean    2001.544296   77053.332094                     1149.05598   
std        7.051905   84956.612897                      709.81215   
min     1990.000000      50.000000                       51.00000   
25%     1995.000000   19919.250000                      593.00000   
50%     2001.000000   38295.000000                     1083.00000   
75%     2008.000000  104676.750000                     1668.00000   
max     2013.000000  501412.000000                     3240.00000   

       pesticides_tonnes      avg_temp  
count       28242.000000  28242.000000  
mean        37076.909344     20.542627  
std         59958.784665      6.312051  
min             0.040000      1.300000  
25%          1702.000000     16.702500  
50%         17529.440000     21.510000  
75%         48687.880000     26.000000  
max        367778.000000     30.650000

In [ ]:
# check for duplicate
data.duplicated().sum()

np.int64(2310)

In [ ]:
# drop the duplicates
data.drop_duplicates(keep='first',inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.shape

(25932, 7)

In [ ]:
data['average_rain_fall_mm_per_year'].unique()

array([1485.,   89., 1010.,  591.,  562.,  534., 1110.,  447., 1292.,
         83., 2666.,  618.,  847.,  416., 1761.,  608.,  748., 1274.,
       1604.,  537., 1342., 1522., 3240., 1113.,  703., 1410., 2274.,
         51., 1784.,  383.,  626.,  536.,  867.,  700., 1187.,  652.,
       1996., 1651., 2387., 1440., 1976.,  589., 1083., 2702.,  216.,
       1118.,  832., 2051., 1668.,  250.,  630.,  641.,  661.,  788.,
         56.,  656., 1513., 1181., 2875.,  282.,   92., 2041.,  758.,
        241.,  346., 1032.,  285., 1500.,  778., 1732., 2280.,  151.,
       1414.,  494., 3142., 1738.,  600.,  854.,   74.,  637., 1212.,
         59.,  686., 1162.,  495.,  636., 1712., 2331.,  624., 1537.,
        691., 1622.,  207.,  593., 1180.,  565., 1220., 1300., 1020.,
        657.])

In [ ]:
data['average_rain_fall_mm_per_year'].dtype

dtype('float64')

In [ ]:
# convert object to float
def isStr(obj):
    try:
        float(obj)
        return False
    except:
        return True

In [ ]:
to_drop = data[data['average_rain_fall_mm_per_year'].apply(isStr)].index

In [ ]:
to_drop

Index([], dtype='int64')

In [ ]:
data = data.drop(to_drop,axis=0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25932 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Area                           25932 non-null  object 
 1   Item                           25932 non-null  object 
 2   Year                           25932 non-null  int64  
 3   hg/ha_yield                    25932 non-null  int64  
 4   average_rain_fall_mm_per_year  25932 non-null  float64
 5   pesticides_tonnes              25932 non-null  float64
 6   avg_temp                       25932 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.6+ MB


In [ ]:
# yield per country
yeild_country = data.pivot_table(
    values='hg/ha_yield',
    index='Area',
    aggfunc='sum'
).sort_values(by='hg/ha_yield',ascending=False)
yeild_country.reset_index(inplace=True)
yeild_country = yeild_country.head(10)
yeild_country

Area  hg/ha_yield
0           India    274219558
1          Brazil    136340329
2          Mexico    113698872
3       Australia    109111062
4           Japan    100924145
5       Indonesia     68067328
6          Turkey     52263950
7        Pakistan     49264956
8           Spain     46773540
9  United Kingdom     44335992

In [ ]:
fig = px.bar(
    yeild_country,
    x='Area',
    y='hg/ha_yield',
    color='hg/ha_yield',
    title='Yield per country',
    text='hg/ha_yield',
    color_continuous_scale=px.colors.sequential.Plasma,
)
fig.update_layout(
    height=1080,
)
fig.show()

In [ ]:
# rearrange the column names
col = ['Year','average_rain_fall_mm_per_year','pesticides_tonnes','avg_temp','Area','Item','hg/ha_yield']
data = data[col]

In [ ]:
data.head()

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp     Area  \
0  1990                         1485.0              121.0     16.37  Albania   
1  1990                         1485.0              121.0     16.37  Albania   
2  1990                         1485.0              121.0     16.37  Albania   
3  1990                         1485.0              121.0     16.37  Albania   
4  1990                         1485.0              121.0     16.37  Albania   

          Item  hg/ha_yield  
0        Maize        36613  
1     Potatoes        66667  
2  Rice, paddy        23333  
3      Sorghum        12500  
4     Soybeans         7000

In [ ]:
data.to_csv('yield_data.csv',index=True)

In [ ]:
data.head(1)

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp     Area  \
0  1990                         1485.0              121.0     16.37  Albania   

    Item  hg/ha_yield  
0  Maize        36613

### Train/Test Split

In [ ]:
X = data.drop('hg/ha_yield',axis=1) #--- > features variable
y = data['hg/ha_yield'] #---> target variable

In [ ]:
X

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  \
0      1990                         1485.0             121.00     16.37   
1      1990                         1485.0             121.00     16.37   
2      1990                         1485.0             121.00     16.37   
3      1990                         1485.0             121.00     16.37   
4      1990                         1485.0             121.00     16.37   
...     ...                            ...                ...       ...   
28237  2013                          657.0            2550.07     19.76   
28238  2013                          657.0            2550.07     19.76   
28239  2013                          657.0            2550.07     19.76   
28240  2013                          657.0            2550.07     19.76   
28241  2013                          657.0            2550.07     19.76   

           Area            Item  
0       Albania           Maize  
1       Albania        Potatoes  
2       Albania     Rice, paddy  
3       Albania         Sorghum  
4       Albania        Soybeans  
...         ...             ...  
28237  Zimbabwe     Rice, paddy  
28238  Zimbabwe         Sorghum  
28239  Zimbabwe        Soybeans  
28240  Zimbabwe  Sweet potatoes  
28241  Zimbabwe           Wheat  

[25932 rows x 6 columns]

In [ ]:
y

0        36613
1        66667
2        23333
3        12500
4         7000
         ...  
28237    22581
28238     3066
28239    13142
28240    22222
28241    22888
Name: hg/ha_yield, Length: 25932, dtype: int64

In [ ]:
# algorithm to train the dataset
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [ ]:
X_train

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  \
24234  2000                           59.0            3024.11     26.55   
9468   2012                          652.0            8002.20     18.82   
6793   2006                         3240.0           98328.63     27.51   
28212  2010                          657.0            3305.17     21.17   
7358   2007                         1410.0            5689.80     27.08   
...     ...                            ...                ...       ...   
23678  2004                          854.0           16942.00     16.31   
5960   2006                          537.0           36572.75      7.85   
860    1991                          534.0           17866.00     18.73   
17223  1998                          250.0            6416.14      6.94   
25918  1994                         2331.0             178.50     26.82   

                     Area            Item  
24234        Saudi Arabia         Sorghum  
9468               Greece  Sweet potatoes  
6793             Colombia           Maize  
28212            Zimbabwe        Potatoes  
7358   Dominican Republic  Sweet potatoes  
...                   ...             ...  
23678            Portugal  Sweet potatoes  
5960               Canada           Wheat  
860             Australia        Potatoes  
17223          Kazakhstan        Potatoes  
25918            Suriname         Cassava  

[20745 rows x 6 columns]

### Converting Categorical to Numerical & Scaling the values

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
ohe = OneHotEncoder(drop='first')
scaler = StandardScaler()

In [ ]:
X_train.head(1)

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  \
24234  2000                           59.0            3024.11     26.55   

               Area     Item  
24234  Saudi Arabia  Sorghum

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('onehotencoder',ohe,[4,5]),
        ('scaler',scaler,[0,1,2,3]),
    ],
    remainder='passthrough'
)

In [ ]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(drop='first'),
                                 [4, 5]),
                                ('scaler', StandardScaler(), [0, 1, 2, 3])])

In [ ]:
# fit the preprocessor on the training data
# scaling the numberical values
X_train_dummy = preprocessor.fit_transform(X_train)
X_test_dummy = preprocessor.transform(X_test)

In [ ]:
X_train_dummy

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 122877 stored elements and shape (20745, 113)>

In [ ]:
X_test_dummy

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30727 stored elements and shape (5187, 113)>

### Train the models

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor


In [ ]:
lr = LinearRegression()
lr.fit(X_train_dummy,y_train)

ls = Lasso()
ls.fit(X_train_dummy,y_train)

rd = Ridge()
rd.fit(X_train_dummy,y_train)

en = ElasticNet()
en.fit(X_train_dummy,y_train)

rf = RandomForestRegressor()
rf.fit(X_train_dummy,y_train)

gb = GradientBoostingRegressor()
gb.fit(X_train_dummy,y_train)

sv = SVR()
sv.fit(X_train_dummy,y_train)

dr = DecisionTreeRegressor()
dr.fit(X_train_dummy,y_train)

kn = KNeighborsRegressor()
kn.fit(X_train_dummy,y_train)


KNeighborsRegressor()

Evaluate

In [ ]:
y_pred1 = lr.predict(X_test_dummy)
y_pred2 = ls.predict(X_test_dummy)
y_pred3 = rd.predict(X_test_dummy)
y_pred4 = en.predict(X_test_dummy)
y_pred5 = rf.predict(X_test_dummy)
y_pred6 = gb.predict(X_test_dummy)
y_pred7 = sv.predict(X_test_dummy)
y_pred8 = dr.predict(X_test_dummy)
y_pred9 = kn.predict(X_test_dummy)

In [ ]:
y_pred1, y_pred2, y_pred3, y_pred4, y_pred5, y_pred6, y_pred7, y_pred8, y_pred9

(array([121054.5433678 ,   7052.34099919,  69893.84018366, ...,
        -27885.7011003 ,  37131.25028885, 185987.97422423]),
 array([121077.68593814,   7257.4205472 ,  69984.17420795, ...,
        -27775.42060864,  36953.0203857 , 185758.81813973]),
 array([120846.33042509,   7189.11659686,  70194.89661517, ...,
        -27586.1565899 ,  36796.47568676, 185974.95469265]),
 array([ 76363.99516625,  62229.56052411,  80435.53453243, ...,
         57888.34437629,  66719.89828862, 112983.94890995]),
 array([126111.1 ,  15533.29,  73310.75, ...,  48103.57,   9600.62,
        130927.83]),
 array([ 69972.34980699,  27317.35201791,  62842.07984506, ...,
         23746.49391883,  24523.67760986, 171690.86661965]),
 array([39004.68518359, 38832.75258131, 39306.89559814, ...,
        38780.93111104, 38702.50575009, 39586.95764576]),
 array([154330.,  15838.,  72614., ...,  52692.,   9621., 132600.]),
 array([126586.2,  15554. ,  72138.2, ...,  50899. ,   9621. , 139136.4]))

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
score1 = r2_score(y_test,y_pred1)
score2 = r2_score(y_test,y_pred2)
score3 = r2_score(y_test,y_pred3)
score4 = r2_score(y_test,y_pred4)
score5 = r2_score(y_test,y_pred5)
score6 = r2_score(y_test,y_pred6)
score7 = r2_score(y_test,y_pred7)
score8 = r2_score(y_test,y_pred8)
score9 = r2_score(y_test,y_pred9)

In [ ]:
score1,score2,score3,score4,score5,score6,score7,score8,score9

(0.7486565660569946,
 0.7485842229351424,
 0.7485420648325525,
 0.23849511353135855,
 0.9844336646324895,
 0.7591769185465314,
 -0.2099498636919488,
 0.9771661284922815,
 0.9823303235521519)

In [ ]:
# checking the error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

# Create an empty list to store results
results = []

def evaluateModel(y_test,y_pred,model_name):

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)


    print(model_name)
    print("------------------------------")
    print("R2 Score:", r2_score(y_test, y_pred))
    print("MSE:", mean_squared_error(y_test, y_pred))
    print()

    results.append({
        'Model': model_name,
        'R2 Score': r2,
        'MSE': mse,
    })



In [ ]:
evaluateModel(y_test,y_pred1,'Linear Regression')
evaluateModel(y_test,y_pred2,'Lasso Regression')
evaluateModel(y_test,y_pred3,'Ridge Regression')
evaluateModel(y_test,y_pred4,'ElasticNet Regression')
evaluateModel(y_test,y_pred5,'Random Forest Regression')
evaluateModel(y_test,y_pred6,'Gradient Boosting Regression')
evaluateModel(y_test,y_pred7,'Support Vector Regression')
evaluateModel(y_test,y_pred8,'Decision Tree Regression')
evaluateModel(y_test,y_pred9,'KNeighbors Regression')

Linear Regression
------------------------------
R2 Score: 0.7486565660569946
MSE: 1821709823.2348366

Lasso Regression
------------------------------
R2 Score: 0.7485842229351424
MSE: 1822234158.2996287

Ridge Regression
------------------------------
R2 Score: 0.7485420648325525
MSE: 1822539715.6337197

ElasticNet Regression
------------------------------
R2 Score: 0.23849511353135855
MSE: 5519304444.753561

Random Forest Regression
------------------------------
R2 Score: 0.9844336646324895
MSE: 112823102.66037074

Gradient Boosting Regression
------------------------------
R2 Score: 0.7591769185465314
MSE: 1745459454.6716852

Support Vector Regression
------------------------------
R2 Score: -0.2099498636919488
MSE: 8769584777.810799

Decision Tree Regression
------------------------------
R2 Score: 0.9771661284922815
MSE: 165497412.74532485

KNeighbors Regression
------------------------------
R2 Score: 0.9823303235521519
MSE: 128067889.63393097



In [ ]:
# Convert results to DataFrame
evaluation_df = pd.DataFrame(results)
evaluation_df

Model  R2 Score           MSE
0             Linear Regression  0.748657  1.821710e+09
1              Lasso Regression  0.748584  1.822234e+09
2              Ridge Regression  0.748542  1.822540e+09
3         ElasticNet Regression  0.238495  5.519304e+09
4      Random Forest Regression  0.984434  1.128231e+08
5  Gradient Boosting Regression  0.759177  1.745459e+09
6     Support Vector Regression -0.209950  8.769585e+09
7      Decision Tree Regression  0.977166  1.654974e+08
8         KNeighbors Regression  0.982330  1.280679e+08

In [ ]:
# visualize the results
final_result = pd.DataFrame({
    'Model':['Linear Regression','Lasso','Ridge','ElasticNet','RandomForest','GradientBoosting','SVR','DecisionTree','KNeighbors'],
    'R2 Score':[score1,score2,score3,score4,score5,score6,score7,score8,score9]
})

final_result

Model  R2 Score
0  Linear Regression  0.748657
1              Lasso  0.748584
2              Ridge  0.748542
3         ElasticNet  0.238495
4       RandomForest  0.984434
5   GradientBoosting  0.759177
6                SVR -0.209950
7       DecisionTree  0.977166
8         KNeighbors  0.982330

In [ ]:
fig = px.bar(
    final_result,
    y='Model',
    x='R2 Score',
    color='Model',
    text_auto=',.0%',
    title='R2 Score of Different Models'
)
fig.update_layout(height=1600)
fig.show()

### Best Model Selection

##### Hyperparameter Tuning

In [ ]:
# Define the models to tune
models = {
    'RandomForestRegressor': RandomForestRegressor(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'KNeighborsRegressor': KNeighborsRegressor()
}

#  Define hyperparameter grids for each model
# param_grids = {
#     'RandomForestRegressor': {
#         'n_estimators': [50, 100, 200],
#         'max_depth': [None, 10, 20, 30],
#         'min_samples_split': [2, 5, 10],
#         'min_samples_leaf': [1, 2, 4],
#         'max_features': ['auto', 'sqrt', 'log2']
#     },
#     'DecisionTreeRegressor': {
#         'max_depth': [None, 3, 5, 10, 20],
#         'min_samples_split': [2, 5, 10, 20],
#         'min_samples_leaf': [1, 2, 4, 8]
#     },
#     'KNeighborsRegressor': {
#         'n_neighbors': [3, 5, 7, 10],
#         'weights': ['uniform', 'distance'],
#         'p': [1, 2]
#     }
# }

param_grids = {
  'RandomForestRegressor': {
    'n_estimators': [100, 200],         # was [50,100,200]
    'max_depth':    [None, 10],         # was [None,10,20,30]
    'max_features': ['sqrt', 'log2'],   # was ['auto','sqrt','log2']
  },
  'DecisionTreeRegressor': {
    'max_depth':        [None, 5, 10],  # was [None,3,5,10,20]
    'min_samples_split': [2, 10],       # was [2,5,10,20]
  },
  'KNeighborsRegressor': {
    'n_neighbors': [3, 7],              # was [3,5,7,10]
    'weights':     ['uniform'],         # was ['uniform','distance']
  }
}


In [ ]:
# import hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
results = {}  # To store the best parameters and evaluation metrics

for model_name, model in models.items():
    print(f"--- Tuning {model_name} ---")



    # search = RandomizedSearchCV(
    #     estimator=model,
    #     param_distributions=param_grids[model_name],
    #     n_iter=20,  # Try 20 random combinations
    #     cv=5,
    #     scoring='neg_mean_squared_error',
    #     n_jobs=-1,
    #     random_state=42
    # )

    # Use GridSearchCV to test all hyperparameter combinations
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=param_grids[model_name],
        cv=3,  # 5-fold cross-validation
        scoring='neg_mean_squared_error',  # Using negative MSE as scoring metric
        n_jobs=-1  # Use all available cores
    )

    # Fit the grid search to the training data
    grid_search.fit(X_train_dummy, y_train)

    # Get the best estimator found by grid search
    best_model = grid_search.best_estimator_

    # Make predictions on the test set using the optimized model
    y_pred = best_model.predict(X_test_dummy)

    # Calculate evaluation metrics
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    # Output the results
    print(f"Best Parameters: {grid_search.best_params_}")
    print(f"R2 Score: {r2}")
    print(f"MAE: {mae}")
    print(f"MSE: {mse}\n")

    # Store results in dictionary for later analysis if needed
    results[model_name] = {
        'best_params': grid_search.best_params_,
        'r2': r2,
        'mae': mae,
        'mse': mse
    }

# Optional: Convert results dictionary to a DataFrame for a cleaner display
results_df = pd.DataFrame(results).transpose()
print("Summary of Hyperparameter Tuning Results:")
print(results_df)

--- Tuning RandomForestRegressor ---
Best Parameters: {'max_depth': None, 'max_features': 'sqrt', 'n_estimators': 200}
R2 Score: 0.977478434776152
MAE: 6396.3262733757465
MSE: 163233850.82823145

--- Tuning DecisionTreeRegressor ---
Best Parameters: {'max_depth': None, 'min_samples_split': 2}
R2 Score: 0.9772737907615243
MAE: 4135.074224021592
MSE: 164717088.34856373

--- Tuning KNeighborsRegressor ---
Best Parameters: {'n_neighbors': 3, 'weights': 'uniform'}
R2 Score: 0.984756449435676
MAE: 4448.0174153332055
MSE: 110483593.57699805

Summary of Hyperparameter Tuning Results:
                                                             best_params  \
RandomForestRegressor  {'max_depth': None, 'max_features': 'sqrt', 'n...   
DecisionTreeRegressor        {'max_depth': None, 'min_samples_split': 2}   
KNeighborsRegressor             {'n_neighbors': 3, 'weights': 'uniform'}   

                             r2          mae               mse  
RandomForestRegressor  0.977478  6396.326273  1

In [ ]:
rf = RandomForestRegressor()
rf.fit(X_train_dummy,y_train)
rf.predict(X_test_dummy)

array([128297.74,  15684.75,  73033.42, ...,  49877.07,   9609.22,
       134802.2 ], shape=(5187,))

In [ ]:
data[(data['Area']=='Saudi Arabia') & (data['Year']==2000) & (data['Item']=='Sorghum')]

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  \
24233  2000                           59.0            3024.11     26.62   
24234  2000                           59.0            3024.11     26.55   

               Area     Item  hg/ha_yield  
24233  Saudi Arabia  Sorghum        13384  
24234  Saudi Arabia  Sorghum        13384

In [ ]:
Year = 2000
average_rain_fall_mm_per_year = 59.0
pesticides_tonnes = 3024.11
avg_temp = 26.55
Area = 'Saudi Arabia'
Item = 'Sorghum'

input_feature = np.array([[Year,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp,Area,Item]])

transformed_features = preprocessor.transform(input_feature).reshape(1,-1)

predicted_value = rf.predict(transformed_features)
predicted_value

array([13323.51])

In [ ]:
data[(data['Area']=='Saudi Arabia') & (data['Year']==2000) & (data['Item']=='Sorghum')]

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  \
24233  2000                           59.0            3024.11     26.62   
24234  2000                           59.0            3024.11     26.55   

               Area     Item  hg/ha_yield  
24233  Saudi Arabia  Sorghum        13384  
24234  Saudi Arabia  Sorghum        13384

In [ ]:
dr = DecisionTreeRegressor()
dr.fit(X_train_dummy,y_train)
dr.predict(X_test_dummy)


array([167489.,  15838.,  72614., ...,  52692.,   9621., 132600.],
      shape=(5187,))

In [ ]:
Year = 2000
average_rain_fall_mm_per_year = 59.0
pesticides_tonnes = 3024.11
avg_temp = 26.55
Area = 'Saudi Arabia'
Item = 'Sorghum'

input_feature = np.array([[Year,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp,Area,Item]])

transformed_features = preprocessor.transform(input_feature).reshape(1,-1)

predicted_value = dr.predict(transformed_features)
predicted_value[0]

np.float64(13384.0)

In [ ]:
# KNN
Year = 2000
average_rain_fall_mm_per_year = 59.0
pesticides_tonnes = 3024.11
avg_temp = 26.55
Area = 'Saudi Arabia'
Item = 'Sorghum'

input_feature = np.array([[Year,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp,Area,Item]])

transformed_features = preprocessor.transform(input_feature).reshape(1,-1)

predicted_value = kn.predict(transformed_features)
predicted_value[0]

np.float64(12529.0)

In [ ]:
# save the model
import joblib

In [ ]:
joblib.dump(dr,'yield_model') # save the model
joblib.dump(preprocessor,'preprocessor') # save the preprocessor

['preprocessor']

In [ ]:
model = joblib.load('yield_model')

In [ ]:
data.head(2)

Year  average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp     Area  \
0  1990                         1485.0              121.0     16.37  Albania   
1  1990                         1485.0              121.0     16.37  Albania   

       Item  hg/ha_yield  
0     Maize        36613  
1  Potatoes        66667

In [ ]:
Year = 1990
average_rain_fall_mm_per_year = 1485.0
pesticides_tonnes = 121.0
avg_temp = 16.37
Area = 'Albania'
Item = 'Potatoes'

In [ ]:
features = np.array([[Year,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp,Area,Item]])

transformed = preprocessor.transform(features).reshape(1,-1)
model.predict(transformed)[0]

np.float64(66667.0)